---
title: "Hobo Loggers"
output: html_document
date: "2025-03-31"
editor_options: 
  chunk_output_type: console
---
Test Commit


```{r setup, include=FALSE}

library(readxl)
library(tidyverse)
library(patchwork)

#This is for plot A

fivetoseven<-read_excel("RCA/RC-A 5-7cm 2025-03-11 16_34_59 AST (Data AST).xlsx")#2/13-2/26
twentytotwentytwo<-read_excel("RCA/RC-A 20-22 cm 2025-03-13 14_01_48 AST (Data AST).xlsx")#2/13-2/14
twentyfivetotwentyseven<-read_excel("RCA/RC-A 25-27cm 2025-03-13 13_33_26 AST (Data AST).xlsx")#2/13-2/23
thirtytothirtytwo<-read_excel("RCA/RC-A 30-32 2025-03-11 16_38_59 AST (Data AST).xlsx")#2/13-3/11
thirtyfivetothirtyseven<-read_excel("RCA/RC-A 35-37 cm 2025-03-11 16_40_56 AST (Data AST).xlsx")#2/13
fortytofortytwo<-read_excel("RCA/RC-A 40-42 2025-03-13 13_31_13 AST (Data AST).xlsx")#2/13-3/5


bottom<-fivetoseven%>%
  filter(`Date-Time (AST)`<=	"2025-02-23 14:20:49")%>%
  ggplot(aes(x=`Date-Time (AST)`, y=`Temperature , °C`))+
geom_point()+
  geom_line()+
  ggtitle("5-7cm")+
  scale_x_datetime()+
  ylim(20,40)

bottom




numthree<-twentyfivetotwentyseven%>%
  filter(`Date-Time (AST)`<=	"2025-02-23 14:20:49")%>%
   ggplot(aes(x=`Date-Time (AST)`, y=`Temperature , °C`))+
geom_point()+
  geom_line()+
  scale_x_datetime()+
   ggtitle("25-27cm")+
  ylim(20,40)
  
numthree

numfour<-thirtytothirtytwo%>%
  filter(`Date-Time (AST)`<=	"2025-02-23 14:20:49")%>%
   ggplot(aes(x=`Date-Time (AST)`, y=`Temperature , °C`))+
geom_point()+
  geom_line()+
  scale_x_datetime()+
   ggtitle("30-32cm")+
  ylim(20,40)

numfour


Numsix<-fortytofortytwo%>%
  filter(`Date-Time (AST)`<=	"2025-02-23 14:20:49")%>%
   ggplot(aes(x=`Date-Time (AST)`, y=`Temperature , °C`))+
geom_point()+
  geom_line()+
  scale_x_datetime()+
   ggtitle("40-42cm")+
  ylim(20,40)


plotA<-Numsix/numfour/numthree/bottom

plotA

```


```{r}

library(readxl)
library(tidyverse)
library(patchwork)

#This is for location C
C10_12<-read_excel("RCC/RC-C 10-12 2025-03-11 14_30_14 AST (Data AST).xlsx")#2/13-3/11 1430
C15_17<-read_excel("RCC/RC-C 15-17 2025-03-11 14_46_17 AST(1).xlsx")#2/13-3/11  14:45
C20_22<- read_excel("RCC/RC-C 20-22 2025-03-11 14_33_43 AST (Data AST).xlsx")#2/13-3/11
C25_27<- read_excel("RCC/RC-C 25-27 cm 2025-03-11 14_28_07 AST (Data AST).xlsx")#2/13-3/11
C30_32<- read_excel("RCC/RC-C 30-32 cm  2025-03-11 14_21_52 AST (Data AST).xlsx")#2/13-3/11
C35_37<- read_excel("RCC/RC-C 35-37 2025-03-11 14_40_31 AST (Data AST).xlsx")#2/13-3/11
C40_42<- read_excel("RCC/RC-C 40-42 2025-03-11 14_19_58 AST (Data AST).xlsx")#2/13-3/11


C1<-C10_12%>%
  ggplot(aes(x=`Date-Time (AST)`, y=`Temperature , °C`))+
geom_point()+
  geom_line()+
  ggtitle("10-12cm")+
  scale_x_datetime()+
  ylim(20,50)

C1




C2<-C15_17%>%
   ggplot(aes(x=`Date-Time (AST)`, y=`Temperature , °C`))+
geom_point()+
  geom_line()+
  scale_x_datetime()+
   ggtitle("15-17cm")+
  ylim(20,50)

C2
  


C3<-C20_22%>%
   ggplot(aes(x=`Date-Time (AST)`, y=`Temperature , °C`))+
geom_point()+
  geom_line()+
  scale_x_datetime()+
   ggtitle("20-22cm")+
  ylim(20,50)

C3


C4<-C25_27%>%
   ggplot(aes(x=`Date-Time (AST)`, y=`Temperature , °C`))+
geom_point()+
  geom_line()+
  scale_x_datetime()+
   ggtitle("25-27cm")+
  ylim(20,50)

C4

C5<-C30_32%>%
   ggplot(aes(x=`Date-Time (AST)`, y=`Temperature , °C`))+
geom_point()+
  geom_line()+
  scale_x_datetime()+
   ggtitle("40-42cm")+
  ylim(20,50)

C5

C6<-C35_37%>%
   ggplot(aes(x=`Date-Time (AST)`, y=`Temperature , °C`))+
geom_point()+
  geom_line()+
  scale_x_datetime()+
   ggtitle("40-42cm")+
  ylim(20,50)

C6

C7<-C40_42%>%
   ggplot(aes(x=`Date-Time (AST)`, y=`Temperature , °C`))+
geom_point()+
  geom_line()+
  scale_x_datetime()+
   ggtitle("40-42cm")+
  ylim(20,50)

C7

plotC<-C7/C6/C5/C4/C3/C2/C1

plotC


```

```{r Water Depths}
library(lubridate)

WaterDepth<- read_excel("HOBO Logger Data.xlsx")
WaterDepth$`Date (mm/dd/yy)`<-ymd(WaterDepth$`Date (mm/dd/yy)`)
WaterDepth$`H2O Depth (x3)A`<-as.numeric(WaterDepth$`H2O Depth (x3)A`)
WaterDepth$`Depth B`<-as.numeric(WaterDepth$`Depth B`)
WaterDepth$`Depth C`<-as.numeric(WaterDepth$`Depth C`)
WaterDepth$`Salinity A`<-as.numeric(WaterDepth$`Salinity A`)
WaterDepth$`Salinity B`<-as.numeric(WaterDepth$`Salinity B`)
WaterDepth$`Salinity C`<-as.numeric(WaterDepth$`Salinity C`)


plotA<-WaterDepth%>%
  filter(`Stake (A, B, C)`=="A")%>%
  ggplot(aes(x=`Date (mm/dd/yy)`,y=`H2O Depth (x3)A`))+
  geom_line()+
  geom_point()+
  ggtitle("Site A")+
  ylim(0,50)

plotA


plotB<-WaterDepth%>%
  filter(`Stake (A, B, C)`=="B")%>%
  ggplot(aes(x=`Date (mm/dd/yy)`,y=`H2O Depth (x3)A`))+
  geom_line()+
  geom_point()+
  ggtitle("Site B")+
  ylim(0,50)

plotB

plotC<-WaterDepth%>%
  filter(`Stake (A, B, C)`=="C")%>%
  ggplot(aes(x=`Date (mm/dd/yy)`,y=`H2O Depth (x3)A`))+
  geom_line()+
  geom_point()+
  ggtitle("Site C")+
  ylim(0,50)

plotC


AVGWaterDepth<-WaterDepth%>%
  group_by(`Stake (A, B, C)`)%>%
  summarise(min(`H2O Depth (x3)A`), max(`H2O Depth (x3)A`))

AVGWaterDepth


Sal<-WaterDepth%>%
  mutate(AVGSal=((`Salinity A`+`Salinity B`+`Salinity C`)/3))%>%
  filter
  

```

